[package]
name = "blanket-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.29.0"
rodio = "0.20.1"
serde = {version = "1.0.219", features = ["derive"]}
toml = "0.8.23"
